name: Publishing

on:
  release:
    types: [published]

jobs:
  build:
    name: Build And publish
    strategy:
      matrix:
        java: ['17']
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle

      - name: Make gradle wrapper executable
        if: ${{ matrix.os != 'windows-latest' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Capture Artefacts
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.java == '17' }}
        uses: actions/upload-artifact@v3
        with:
          path: app/build/libs/
          name: Jars

      - name: Upload Assets
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.java == '17' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app/build/libs/mccg-${{ env.VERSION }}.jar
          asset_name: MCCG-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive

